# Site settings
title: Information Assurance Student Group  
email: drahos@iastate.edu
description: > # this means to ignore newlines until "baseurl:"
    This is the website of the Information Assurance Student Group (IASG)
    at Iowa State University. IASG holds weekly meetings on information
    security topics. These meetings consist of convention-style
    presentations about various infosec-related topics including
    hacking, exploits, recent vulnerabilities in the news, OWASP Tope Ten
    webapp vulnerabilities, and general hacker subjects such as 
    radio, operating systems, and networking.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://iasg.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username: drahosj

# Build settings
markdown: kramdown
