# Site settings
title: Information Assurance Student Group  
email: iasg-cabinet@iastate.edu
description: > # this means to ignore newlines until "baseurl:"
    The Information Assurance Student Group (IASG), part of the Information
    Assurance Center at Iowa State is dedicated to
    information security and holds weekly meetings for students interested in the
    infosec field.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://iasg.iac.iseage.org" # the base hostname & protocol for your site
twitter_username: 
github_username: IASG
facebook_page: infasgroup
youtube_channel: UC-rLOtGfHGx9N1mlNNEwJNQ

# Build settings
markdown: kramdown

exclude: [vendor]
